//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module TZTestWeb.Models {
	export class ColumnsSection
	{
		public Columns: TZTestWeb.Models.LockersSection[];
	}
	export class LockersSection
	{
		public Lockers: TZTestWeb.Models.Locker[];
	}
	export class Locker
	{
		public Name: string;
		public Size: number;
	}
}
